### ISSUE TITLE
Provider package dependency error

### ISSUE THREAD

**Issue by ValYouW** [mehdizarepour/instagram-text-editor#14]
Hi,

I just added Provider 6.0 to my app and got an error running "pub get". text_editor is dependent on Provider 5.0 and my app needs Provider 6.0.
I am new to flutter, can this be easily solved? (I am used to node.js dependencies where such things are a no issue).
If not then I think that using Provider in this package is problematic, as a "utility package" it is a problem for it to prevent apps using this package from using whatever version of another "utility package" (ie Provider).

In any case, thank you for sharing this package !

**Comment by mehdizarepour** [comment]
Hi, @ValYouW

Thank you for opening this issue, I've upgraded `Provider` package's version to `6.0.1` and it's available on `0.6.0`.
I'm closing this issue, feel free to reopen it if you have any problems.

thanks.

**Comment by ValYouW** [comment]
@mehdizarepour Thank you very much!! really appreciate it. 
I would still consider not using Provider in this package as this issue will rise every time there is a mismatch between this package and the "hosting" app, but your call :)
Thanks again!

**Comment by mehdizarepour** [comment]
@ValYouW I know what you are mentioning, I will do that one day when I had time ;)
I've had a background from Nodejs too and I didn't know there's a problem like this in Flutter! and also you're welcome to open a PR ;)

Thanks!

**Comment by ValYouW** [comment]
If you are open to PR I'll be happy to try!
