### ISSUE TITLE
Placeholder text is still present even after adding the text

### ISSUE THREAD

**Issue by xbadal** [mehdizarepour/instagram-text-editor#5]
![WhatsApp Image 2021-04-08 at 11 43 25](https://user-images.githubusercontent.com/13783485/113977114-b7ecda00-985f-11eb-8022-130120ac15ab.jpeg)

**Comment by mehdizarepour** [comment]
Hi @xbadal, thank you for opening this issue.
Can you please share me more details? Can’t you close the editor after editing a text?

**Comment by xbadal** [comment]
I have attached a screenshot.

**Comment by mehdizarepour** [comment]
Do you use `showGeneralDialog` to show the editor? If yes you need to call `Navigator.pop(context);` on `onEditCompleted` event to close your `Dialog`:

```dart
onEditCompleted: (style, align, text) {
  setState(() {
    _text = text;
    _textStyle = style;
    _textAlign = align;
  });
  Navigator.pop(context);
},
```

**Full example:**
```diff
showGeneralDialog(
  context: context,
  barrierDismissible: false,
  transitionDuration: Duration(
    milliseconds: 400,
  ),
  pageBuilder: (_, __, ___) {
    return Container(
      color: Colors.black.withOpacity(0.4),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        body: SafeArea(
          child: Container(
            child: TextEditor(
              fonts: fonts,
              text: text,
              textStyle: textStyle,
              textAlingment: textAlign,
              onEditCompleted: (style, align, text) {
               setState(() {
                  _text = text;
                  _textStyle = style;
                  _textAlign = align;
                });
+               Navigator.pop(context);
              },
            ),
          ),
        ),
      ),
    );
  },
);
```
Also, you can see the [example](https://github.com/mehdizarepour/instagram-text-editor/blob/master/example/lib/main.dart) that I've prepared before too. If you still have a problem with it, please share some code.

**Comment by xbadal** [comment]
I am doing the same. I have attached the code here. please help



  void _tapHandler(text, textStyle, textAlign) {
    showGeneralDialog(
      context: context,
      barrierDismissible: false,
      transitionDuration: Duration(
        milliseconds: 400,
      ), // how long it takes to popup dialog after button click
      pageBuilder: (_, __, ___) {
        // your widget implementation
        return Container(
          color: Colors.black.withOpacity(0.4),
          child: Scaffold(
            backgroundColor: Colors.transparent,
            body: SafeArea(
              // top: false,
              child: Container(
                child: TextEditor(
                  fonts: fonts,
                  text: text,
                  textStyle: textStyle,
                  textAlingment: textAlign,
                  // paletteColors: [
                  //   Colors.black,
                  //   Colors.white,
                  //   Colors.blue,
                  //   Colors.red,
                  //   Colors.green,
                  //   Colors.yellow,
                  //   Colors.pink,
                  //   Colors.cyanAccent,
                  // ],
                  // decoration: EditorDecoration(
                  //   doneButton: Icon(Icons.close, color: Colors.white),
                  //   fontFamily: Icon(Icons.title, color: Colors.white),
                  //   colorPalette: Icon(Icons.palette, color: Colors.white),
                  //   alignment: AlignmentDecoration(
                  //     left: Text(
                  //       'left',
                  //       style: TextStyle(color: Colors.white),
                  //     ),
                  //     center: Text(
                  //       'center',
                  //       style: TextStyle(color: Colors.white),
                  //     ),
                  //     right: Text(
                  //       'right',
                  //       style: TextStyle(color: Colors.white),
                  //     ),
                  //   ),
                  // ),
                  onEditCompleted: (style, align, text) {
                    setState(() {
                      _text = text;
                      _textStyle = style;
                      _textAlign = align;
                    });
                    Navigator.pop(context);
                  },
                ),
              ),
            ),
          ),
        );
      },
    );
  }

**Comment by xbadal** [comment]
I think text needs to hide while editing

**Comment by mehdizarepour** [comment]
> I am doing the same. I have attached the code here. please help

Can you produce an example of your code?

> I think text needs to hide while editing

If you mean the text behind the Editor, It's totally your choice. for example you can wrap your `Text` widget with a `Visibility` widget then you can control the visibility of your `Text` widget.

```diff
  void tapHandler(text, textStyle, textAlign) {
    showGeneralDialog(
      context: context,
      barrierDismissible: false,
      transitionDuration: Duration(
        milliseconds: 400,
      ),
      pageBuilder: (_, __, ___) {
        return Container(
          color: Colors.black.withOpacity(0.4),
          child: Scaffold(
            backgroundColor: Colors.transparent,
            body: SafeArea(
              child: Container(
                child: TextEditor(
                  fonts: fonts,
                  text: text,
                  textStyle: textStyle,
                  textAlingment: textAlign,
                  onEditCompleted: (style, align, text) {
                    setState(() {
                      _text = text;
                      _textStyle = style;
                      _textAlign = align;
+                    visable = true;
                    });
                    Navigator.pop(context);
                  },
                ),
              ),
            ),
          ),
        );
      },
    );
  }
```

```diff
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: SafeArea(
        top: false,
        child: Center(
          child: Stack(
            children: [
              Image.asset('assets/story.png'),
              Center(
                child: GestureDetector(
                  onTap: () {
+                  setState(() {
+                    visable = false;
+                  });
                    tapHandler(_text, _textStyle, _textAlign);
                  },
+                 child: Visibility(
+                  visible: visable,
                    child: Text(
                      _text,
                      style: _textStyle,
                      textAlign: _textAlign,
                    ),
+                ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
```

**Comment by xbadal** [comment]
i got it. thanks!
