### ISSUE TITLE
Add text background color

### ISSUE THREAD

**Issue by azazadev** [mehdizarepour/instagram-text-editor#6]
First of all Thanks for this nice package !

any plan to support text background color ?
I can see it's for TODO and Widget is already there 

```
                    // TODO: Add text background color
                      // SizedBox(width: 20),
                      // TextBackgroundColor(),
```

**Comment by mehdizarepour** [comment]
Hi @azazadev, Thank you for opening this issue.
Actually, I was going to add this feature but I'm not sure about its UX but I'm working on it and I will do it as soon as I can.

**Comment by mahdyar** [comment]
> Hi @azazadev, Thank you for opening this issue.
> Actually, I was going to add this feature but I'm not sure about its UX but I'm working on it and I will do it as soon as I can.

@mehdizarepour How about a white background with colorful border (reversed color option)? 

Additionally, I'd like to make a PR to address this issue, but since it's assigned to you, I wanted to ask first, so may I?

**Comment by mehdizarepour** [comment]
Hi @mahdyar.

What do you mean by a white background with a colorful border? Can you please explain a little more?
I wanted it to be like Instagram's background feature.

**Comment by mahdyar** [comment]
> Hi @mahdyar.
> 
> What do you mean by a white background with a colorful border? Can you please explain a little more?
> I wanted it to be like Instagram's background feature.

You mean this one?

![20210815_115011.jpg](https://user-images.githubusercontent.com/20593549/129470451-33f8e642-e7dc-4d74-9c48-881bd31f043e.jpg)

**Comment by mehdizarepour** [comment]
@mahdyar Yes, Exactly!

**Comment by mahdyar** [comment]
> @mahdyar Yes, Exactly!

Okay, I'm on it! :)

**Comment by mehdizarepour** [comment]
Ok, Great!
Just consider the Contributing instruction. ;)

**Comment by mahdyar** [comment]
> Ok, Great!
> Just consider the Contributing instruction. ;)

Any idea on how to detect if text color is light so the background should be black or if it's dark and background should be white? or even if it's what you want it to do? 🤔

**Comment by mehdizarepour** [comment]
Hi @azazadev, the Text background color feature will be available on `0.5.0` version.
Demo:


https://user-images.githubusercontent.com/8446770/129958417-b17ad9bd-d5ad-42f3-8f7d-b19bcc5b0016.mp4

**Comment by mehdizarepour** [comment]
@azazadev I'm gonna close this issue, feel free to reopen if you had any problems.

**Comment by bdlukaa** [comment]
Any way to do this type of text background?

![photo1635596460](https://user-images.githubusercontent.com/45696119/140644446-6d668826-2632-4e9f-a30e-1460b6b4ca21.jpeg)

**Comment by mehdizarepour** [comment]
Hi, @bdlukaa.

I tried using `background` instead of `backgroundColor like this:

```dart
background: Paint()
                  ..style = PaintingStyle.fill
                  ..color = Colors.red
                  ..strokeJoin = StrokeJoin.round
                  ..strokeCap = StrokeCap.round,
```

But it didn't work! and also I tried `CutomPainter` too but it didn't work either.
Do you have any solution?

**Comment by bdlukaa** [comment]
I have something. I started working on this with custom painter, but it is a very intial solution. Will be looking forward to be working together
![2021-11-07 (2)](https://user-images.githubusercontent.com/45696119/140646198-978baf3a-b872-427a-becf-85a3a571d8cb.png)

You can add me on discord: bdlukaa#4828
